### ISSUE TITLE
Provide some way to hook into client-side zoom events

### ISSUE THREAD

**Issue by zachmullen** [Kitware/trame-plotly#2]
Would be nice if we could bind a callback when the user zooms a plot on the front-end.

**Comment by jourdain** [comment]
Is that not already supported?

**Comment by zachmullen** [comment]
@psavery can you provide more detail on what you said was not able to be accomplished currently?

**Comment by psavery** [comment]
I chatted with Seb. We can hook into these events from plotly [here](https://github.com/Kitware/trame-plotly/blob/036444f8ed4c1747c1157f86fcfbf20760b6af66/trame_plotly/widgets/plotly.py#L40-L66). There may be one that is zoom-related (or there may be another one not on the list that we need to add). Will need to do more research.

**Comment by jourdain** [comment]
Closing since it was available all along
